apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: arris-exporter
    app.kubernetes.io/name: arris-exporter
  name: arris-exporter
  namespace: observability
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: PreferDualStack
  ports:
    - name: http
      port: 9706
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: arris-exporter
    app.kubernetes.io/name: arris-exporter
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
