apiVersion: v1
kind: Service
metadata:
  name: alloy-tcp-logs
  namespace: observability
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/part-of: alloy
spec:
  type: NodePort
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  selector:
    app.kubernetes.io/instance: alloy
    app.kubernetes.io/name: alloy
  ports:
    - name: tcp-logs
      protocol: TCP
      port: 30514
      targetPort: 30514
      nodePort: 30514
