---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ndppd-config
  namespace: kube-system
data:
  ndppd.conf: |
    route-ttl 30000
    proxy enp0s25 {
        router no
        timeout 500
        ttl 30000
        rule fd1f:5691:b710:8::/64 {
            static
        }
    }
