---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: lb-pool
spec:
  allowFirstLastIPs: "No"
  blocks:
    - cidr: 192.168.8.16/28
    - cidr: fdb6:e5da:a7b8:d3a2::/112
